<?php

use App\Actions\Emissions\HomologatePuCurve;
use App\Domain\PuCalculator\Enums\PuCurveStatus;
use App\Domain\PuCalculator\Exceptions\PuMakerCheckerException;
use App\Enums\BusinessArea;
use App\Filament\Resources\Emissions\Pages\EditEmission;
use App\Models\Area;
use App\Models\Emission;
use App\Models\EmissionPuCurveVersion;
use App\Models\User;
use Database\Seeders\RolesAndPermissionsSeeder;
use Filament\Actions\Action;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Spatie\Activitylog\Models\Activity;
use Spatie\Permission\PermissionRegistrar;

uses(RefreshDatabase::class);

beforeEach(function () {
    app(PermissionRegistrar::class)->forgetCachedPermissions();
    $this->seed(RolesAndPermissionsSeeder::class);
});

function makeGeneratedVersion(int $generatedBy, PuCurveStatus $status = PuCurveStatus::Generated): array
{
    $emission = Emission::factory()->create(['type' => 'CRI', 'status' => 'active']);
    EmissionPuCurveVersion::factory()->create([
        'emission_id' => $emission->id,
        'calculation_version' => 'v1',
        'status' => $status->value,
        'generated_by' => $generatedBy,
    ]);

    return [$emission, $generatedBy];
}

function makePuAreaResponsible(User $user): void
{
    Area::for(BusinessArea::PuCurve)->responsibles()->attach($user->id);
}

function homologatedVersionOf(Emission $emission): EmissionPuCurveVersion
{
    return EmissionPuCurveVersion::query()->where('emission_id', $emission->id)->sole();
}

it('blocks homologation when the checker generated the curve', function () {
    $maker = User::factory()->create();
    [$emission] = makeGeneratedVersion($maker->id);

    expect(fn () => app(HomologatePuCurve::class)->handle($emission, 'v1', $maker->id))
        ->toThrow(PuMakerCheckerException::class);

    expect(EmissionPuCurveVersion::query()->where('emission_id', $emission->id)->first()->status)
        ->toBe(PuCurveStatus::Generated);
});

it('allows a different checker to homologate the curve', function () {
    $maker = User::factory()->create();
    $checker = User::factory()->create();
    [$emission] = makeGeneratedVersion($maker->id);

    app(HomologatePuCurve::class)->handle($emission, 'v1', $checker->id);

    expect(EmissionPuCurveVersion::query()->where('emission_id', $emission->id)->first()->status)
        ->toBe(PuCurveStatus::Homologated);
});

it('no longer lets a super-admin skip the segregation just for the role', function () {
    $superAdmin = User::factory()->create();
    $superAdmin->assignRole('super-admin');
    [$emission] = makeGeneratedVersion($superAdmin->id, PuCurveStatus::Validated);

    expect(fn () => app(HomologatePuCurve::class)->handle($emission, 'v1', $superAdmin->id, 'Conferida.'))
        ->toThrow(PuMakerCheckerException::class, 'responsável da área Curva de PU e Índices');

    expect(homologatedVersionOf($emission)->status)->toBe(PuCurveStatus::Validated);
});

it('lets the PU area responsible homologate a validated curve they generated, with justification', function () {
    $responsible = User::factory()->create();
    makePuAreaResponsible($responsible);
    [$emission] = makeGeneratedVersion($responsible->id, PuCurveStatus::Validated);

    app(HomologatePuCurve::class)->handle($emission, 'v1', $responsible->id, '  Bate com a curva do sistema antigo.  ');

    $version = homologatedVersionOf($emission);
    $activity = Activity::query()->where('description', 'pu_curve_homologated')->sole();

    expect($version->status)->toBe(PuCurveStatus::Homologated)
        ->and($version->homologated_by)->toBe($responsible->id)
        ->and($version->self_homologated)->toBeTrue()
        ->and($version->homologation_justification)->toBe('Bate com a curva do sistema antigo.')
        ->and($activity->properties['self_homologated'])->toBeTrue()
        ->and($activity->properties['justification'])->toBe('Bate com a curva do sistema antigo.')
        ->and($activity->properties['authorized_by_area'])->toBe(BusinessArea::PuCurve->value);
});

it('also covers the responsible who validated the curve generated by someone else', function () {
    $responsible = User::factory()->create();
    makePuAreaResponsible($responsible);
    [$emission] = makeGeneratedVersion(User::factory()->create()->id, PuCurveStatus::Validated);
    homologatedVersionOf($emission)->forceFill(['validated_by' => $responsible->id])->save();

    expect(fn () => app(HomologatePuCurve::class)->handle($emission, 'v1', $responsible->id))
        ->toThrow(PuMakerCheckerException::class, 'justificativa');

    app(HomologatePuCurve::class)->handle($emission, 'v1', $responsible->id, 'Validação sem divergências.');

    expect(homologatedVersionOf($emission)->self_homologated)->toBeTrue();
});

it('keeps the responsible from homologating their own curve before it passes the spreadsheet validation', function (PuCurveStatus $status) {
    $responsible = User::factory()->create();
    makePuAreaResponsible($responsible);
    [$emission] = makeGeneratedVersion($responsible->id, $status);

    expect(fn () => app(HomologatePuCurve::class)->handle($emission, 'v1', $responsible->id, 'Conferida.'))
        ->toThrow(PuMakerCheckerException::class, 'validação contra planilha');

    expect(homologatedVersionOf($emission)->status)->toBe($status);
})->with([
    'gerada, sem validação' => [PuCurveStatus::Generated],
    'divergente' => [PuCurveStatus::Divergent],
]);

it('requires a justification from the responsible homologating their own curve', function () {
    $responsible = User::factory()->create();
    makePuAreaResponsible($responsible);
    [$emission] = makeGeneratedVersion($responsible->id, PuCurveStatus::Validated);

    expect(fn () => app(HomologatePuCurve::class)->handle($emission, 'v1', $responsible->id, '   '))
        ->toThrow(PuMakerCheckerException::class, 'justificativa');

    expect(homologatedVersionOf($emission)->status)->toBe(PuCurveStatus::Validated);
});

it('does not mark a homologation by a different checker as self-homologation', function () {
    $checker = User::factory()->create();
    [$emission] = makeGeneratedVersion(User::factory()->create()->id);

    app(HomologatePuCurve::class)->handle($emission, 'v1', $checker->id, 'Conferida por amostragem.');

    $version = homologatedVersionOf($emission);

    expect($version->self_homologated)->toBeFalse()
        ->and($version->homologation_justification)->toBe('Conferida por amostragem.');
});

it('asks for the justification on screen when the responsible homologates their own curve', function () {
    $responsible = makeAdminUser();
    makePuAreaResponsible($responsible);
    [$emission] = makeGeneratedVersion($responsible->id, PuCurveStatus::Validated);
    $this->actingAs($responsible);

    Livewire::test(EditEmission::class, ['record' => $emission->getRouteKey()])
        ->assertActionExists('homologatePuCurve', fn (Action $action): bool => str_contains((string) $action->getModalDescription(), 'Como responsável pela área Curva de PU e Índices'))
        ->mountAction('homologatePuCurve')
        ->callMountedAction(['justification' => ''])
        ->assertHasActionErrors(['justification' => 'required']);

    Livewire::test(EditEmission::class, ['record' => $emission->getRouteKey()])
        ->callAction('homologatePuCurve', data: ['justification' => 'Bate com o sistema antigo.'])
        ->assertHasNoActionErrors();

    expect(homologatedVersionOf($emission)->homologation_justification)->toBe('Bate com o sistema antigo.');
});

it('explains on screen why someone who is not the responsible cannot homologate their own curve', function () {
    $maker = makeAdminUser();
    [$emission] = makeGeneratedVersion($maker->id, PuCurveStatus::Validated);
    $this->actingAs($maker);

    Livewire::test(EditEmission::class, ['record' => $emission->getRouteKey()])
        ->assertActionExists('homologatePuCurve', fn (Action $action): bool => str_contains((string) $action->getModalDescription(), 'Ela precisa ser homologada por outra pessoa'));
});
