[program:bsi-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/bsicapital/artisan queue:work redis --sleep=1 --tries=3 --timeout=120
autostart=true
autorestart=true
numprocs=1
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/bsi-queue.log
stopwaitsecs=3600
